// This time the flag that the user must enter is dynamically generated by a flag() function
// The flag is workshop{SuperSecretLevel2} but is not stored in plain text anywhere

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

char *flag()
{
    char *flag = malloc(40);
    strcpy(flag, "\x54\x4c\x51\x48\x50\x4b\x4c\x53\x58\x70\x56\x53\x46\x51\x70\x46\x40\x51\x46\x57\x6f\x46\x55\x46\x4f\x11\x5e");
    for (int i = 0; i < strlen(flag); i++)
    {
        flag[i] = flag[i] ^ 0x23;
    }
    return flag;
}

int main(int argc, char *argv[])
{
    char password[40];
    printf("Enter the password: ");
    scanf("%s", password);
    if (strcmp(password, flag()) == 0)
    {
        printf("Correct password");
        return 0;
    }
    else
    {
        printf("Incorrect password");
        return 3;
    }
}
